### ISSUE TITLE
Gerät registrieren

### ISSUE THREAD

**Issue by mdroessler** [DeviceRegistration/Frontend#16]
Die weiteren Device-Features brauchen vorher angelegte Daten. Der Button "Create new Device" soll ein neues Gerät erstellen und gleich im Backend anlegen.

**Comment by MuhammedErek** [comment]
Error im Response Header: Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight.
Backend wurde informiert

Status äquivalent zu Tickets: Geräteinformationen anzeigen und Geräte bearbeiten

**Comment by MuhammedErek** [comment]
Der Response Header des lokalen Servers ist vollkommen unterschiedlich zum live Server.
Im Header fehlt der Access-Control-Allow-Origin Header und noch etliche weitere.
Warum ist mir nicht klar...
Aus dem Grund funktioniert es mit der lokalen Version sogar noch schlimmer als mit der Live Version.
Es ist dringend Hilfe bzw. ein Ausweg gesucht.

**Comment by mdroessler** [comment]
Ich hab mal beim Backend Team nachgefragt. Vielleicht wissen sie da genaueres.

**Comment by mdroessler** [comment]
Ok Rückmeldung vom Backend.
Auf dem TSF ist die Version an der sie gerade arbeiten. Das ist nicht die gleiche wie bei der Live-Version.

**Comment by MuhammedErek** [comment]
Habe super Neuigkeiten.
Das Backend musste wirklich nur das tun, was ich denen immer gesagt hatte.
Dieses Acces-Control Feld musste bei denen mitgeschrieben werden. 
Habe das nun mit Absprache mit Patrick bei mir lokal getestet und der Error ist weg.
Jetzt werden die das bei der neuen live Version mit einbeziehen und die Kommunikation mit dem Backend sollte funktionieren :)
Jetzt bestehen im Rahmen dieses Tickets nur noch Errors mit Code 400, welche ich versuche zu beseitigen.
