### ISSUE TITLE
New Device - Felder Korrektur

### ISSUE THREAD

**Issue by mdroessler** [DeviceRegistration/Frontend#17]
Statt der frei wählbaren Felder "Maintenance" und "Notification" soll es zwei wählbare Felder "Maintenance" und "Calibration" geben.
In jedem Feld gibt es die Inputs "Interval" und "Period start", und die optionalen Inputs für Notifications "Reminder"  und "E-mail".

**Comment by MuhammedErek** [comment]
Das Kalibrierungsfeld wurde zur Vollständigkeit hinzugefügt und Notification und das dazugehörige Feld (Wartung bzw. Kalibrierung) wurden zusammengepackt.

**Comment by Fudra** [comment]
@MuhammedErek  Erstell bitte ein pull-request, dass dein Code in den Develop in dem Aktuellen Repository und nicht in den Repository gemerged wird, von dem das Projekt geklont wurde.
