### ISSUE TITLE
CSS Übersicht

### ISSUE THREAD

**Issue by mdroessler** [DeviceRegistration/Frontend#2]
Eine Auflistung der CSS Klassen und entsprechenden Beispielen.
Soll als Erleichterung für die Entwicklung dienen.

**Comment by Fudra** [comment]
Das Doc wird mit [Jekyll](http://jekyllrb.com/) gebaut.'Jekyll' ist ein Statischer-Content-Generator. Es bietet ein Syntax-highlighting sowie kann auch von Githup unter dem Branch 'githup-pages' gehostet werden.
